// <auto-generated />
namespace Market_Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_cat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_cat));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201521369_add_cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
